config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  devise_for :users,
             controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users/registrations"
             }

  # privacy policy and terms of service - for Twitter authentication
  get "/terms", to: redirect("/terms.html")
  get "/privacy", to: redirect("/privacy.html")

  # NewsItem compatibility with old wordpress Posts url
  get "/:year/:month/:slug",
      to: "news_items#show",
      constraints: { year: /\d{4}/, month: /\d{2}/ }
  resources :news_items, only: %i(index show)

  resources :events, only: %i(index show)
  resources :organizations, only: %i(index show)
  resources :jobs, only: %i(index show new create) do
    member do
      get :confirmation
    end
  end

  resources :pages, only: [:show]
  resource :member, only: %i(create edit update), path: :profile
  resources :talks, only: %i(new create show)

  root "home#index"
end

app/models/job.rb
# frozen_string_literal: true

class Job < ActiveRecord::Base
  extend Enumerize
  include Authorable
  STATES = %w(draft published archived).freeze

  before_save :set_published_at, if: proc { state_changed?(to: "published") }

  belongs_to :organization

  scope :published, -> { where(state: :published).order(created_at: :desc) }
  scope :search, -> (query = nil) { where("LOWER(title) LIKE LOWER(?) OR LOWER(description) LIKE LOWER(?)", "%#{query}%", "%#{query}%") if query }
  scope :draft, -> { where(state: :draft) }

  enumerize :state, in: STATES, default: :draft

  validates :title,
            presence: true,
            length: { maximum: MAX_STRING_COLUMN_LENGTH }
  validates :description,
            presence: true,
            length: { maximum: MAX_TEXT_COLUMN_LENGTH }
  validates :state,
            presence: true,
            inclusion: { in: STATES }

  accepts_nested_attributes_for :organization

  private

  def set_published_at
    # We can't use touch since it only work on persisted object
    self.published_at = DateTime.current
  end
end

app/controllers/admin/jobs_controller.rb
# frozen_string_literal: true

module Admin
  class JobsController < Admin::ApplicationController
    include AdministrateCustomization

    private

    def order
      @_order ||= Administrate::Order.new(params.fetch(:order, :published_at),
                                          params.fetch(:direction, :desc))
    end
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, only: [:show]
  before_action :authenticate_user!, only: %i(new create)
  after_action :verify_authorized, only: %i(new create confirmation)

  # No job is find, because the job is not in draft mode anymore
  # or wasn't create by the current user.
  # Redirect the user to the job listing
  rescue_from Pundit::NotAuthorizedError, with: :cant_access_confirmation

  # GET /jobs/new
  def new
    # The organization needs to be built to display the nested form
    @job = Job.new(user_id: current_user.id).tap(&:build_organization)
    authorize @job
  end

  # POST /jobs
  def create
    @job = Job.new(permitted_attributes.merge(user_id: current_user.id))
    authorize @job

    if @job.save
      flash[:notice] = "The job posting has been send for review. Thanks!"
      redirect_to confirmation_job_url(@job)
    else
      render :new
    end
  end

  # GET /jobs/1/confirmation
  def confirmation
    @job = Job.find params[:id]
    authorize @job

    render :show
  end

  # GET /jobs
  def index
    @jobs = Job.published.includes(:organization).search(params[:query])
  end

  # GET /jobs/1
  def show; end

  private

  def set_job
    @job = Job.published.find(params[:id])
  end

  def permitted_attributes
    attributes = params.require(:job).permit(:title,
                                             :description,
                                             organization_attributes: %i(name address))

    attributes_with_organization(attributes)
  end

  def cant_access_confirmation
    redirect_to(jobs_url) && return
  end

  def attributes_with_organization(attributes)
    # Memorize organization in case this method is called more than once
    @organization ||= Organization.find_by_name(attributes.dig(:organization_attributes, :name))

    if @organization.present?
      # In the case the organization already exist, we don't want to create a new one
      # Remove the attributes and assign the organization id
      attributes.delete(:organization_attributes)
      attributes[:organization_id] = @organization.id
    end

    attributes
  end
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, class: "form-control" %>
    <small class='text-danger'>
      <%= @job.errors.full_messages_for(:title).to_sentence %>
    </small>
  </div>

  <div class="form-group">
    <%= f.label :description %><br/>
    <%= f.text_area :description, class: "form-control", rows: "5" %>
    <small class='text-danger'>
      <%= @job.errors.full_messages_for(:description).to_sentence %>
    </small>
    <div class="joblint-issues">
      <a class="btn btn-primary joblint-issue" type="button">
        Culture <span id="culture-issues-num" class="badge">0</span>
      </a>
      <a class="btn btn-primary joblint-issue" type="button">
        Realism <span id="realism-issues-num" class="badge">0</span>
      </a>
      <a class="btn btn-primary joblint-issue" type="button">
        Recruiter <span id="recruiter-issues-num" class="badge">0</span>
      </a>

      <a class="btn btn-primary joblint-issue" type="button">
        Sexism <span id="sexism-issues-num" class="badge">0</span>
      </a>

      <a class="btn btn-primary joblint-issue" type="button">
        Tech <span id="tech-issues-num" class="badge">0</span>
      </a>
    </div>
    <div class='joblint-issue-desc-container list-group'></div>
  </div>

  <hr/>

  <%= f.fields_for :organization do |o| %>
    <div class="form-group">
      <%= o.label :name, 'Organization Name' %><br/>
      <%= o.text_field :name, class: "form-control" %>
      <small class='text-danger'>
        <%= @job.organization.errors.full_messages_for(:name).to_sentence %>
      </small>
    </div>

    <div class="form-group">
      <%= o.label :address, 'Organization Address' %><br/>
      <%= o.text_field :address, class: "form-control" %>
      <small class='text-danger'>
        <%= @job.organization.errors.full_messages_for(:address).to_sentence %>
      </small>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit 'Submit a job posting', class: 'btn btn-primary' %><br/>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h2><%= link_to render_markdown_as_html(job.title), job_path(job) %></h2>

<div class="meta">
  <% if job.organization %>
    <%= icon 'building', class: 'fa-fw' %><%= job.organization.name  %><br/>
  <% end %>

  <p><%= icon 'calendar-o', class: 'fa-fw' %>Posted <%= time_ago_in_words(job.created_at) %> ago</p>
  <% if job.organization.logo.present? %>
    <%= link_to image_tag(job.organization.logo.thumbnail.url, alt: render_markdown_as_html(job.organization.name)), organization_path(job.organization) %>
  <% end %>
</div>

<div class="markdown-body">
  <%=  render_markdown_as_html job.description  %>
</div>

<hr/>

app/views/jobs/index.html.erb
<% provide :title, 'Jobs' %>

<h1>Listing Jobs</h1>

<%= form_tag(jobs_path, method: "get") do %>
  <div class="col-md-11 col-sm-8 col-xs-5">
    <%= text_field_tag(:query, "", { class: "form-control", placeholder: "Awesome job" }) %>
  </div>
  <div class="col-md-1 col-sm-4 col-xs-5">
    <%= submit_tag("Search", class: "btn btn-primary") %>
  </div>
<% end %>

<%= render @jobs %>

app/views/jobs/new.html.erb
<% provide :title, 'Submit a job posting' %>
<h1>Submit a job posting</h1>

<%= render partial: 'form' %>

app/views/jobs/show.html.erb
<%= render @job %>